import { Box } from "@chakra-ui/react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Box h="full">
      {children}
    </Box>
  );
}
